version: '3'

services:

  datachannel-service:
    image: "nimbleplatform/data-channel-service:latest"
    ports:
        - "9099:9099"
    environment:
      DATACHANNEL_DB_HOST: "dev-main-db"
      DATACHANNEL_DB_HOST_PORT: "5432"
      DATACHANNEL_DB_NAME: "datachanneldb"
      DATACHANNEL_DB_USERNAME: "postgres"
      DATACHANNEL_DB_PASSWORD: "postgres"
      IDENTITY_SERVICE_URL: "http://identity-service/identity"
      LOCAL_DATA_PIPE: ""
      # internal url (not publicly exposed) / leave empty if want only private data channel
      LOCAL_DCFS: ""
      # internal url (not publicly exposed) / leave empty if want only private data channel
      DATA_PIPE_URL: ""  
      # external url / leave empty if want only private data channel
      DCFS_URL: ""
      # external url / leave empty if want only private data channel
    networks:
      - infra
    